---
swagger: "2.0"
info:
  description: "Data Utility Evaluator"
  version: "0.2.1"
  title: "Data Utility Evaluator API"
  contact:
    email: "pierluigi.plebani@polimi.it"
  license:
    name: "TBD"
host: "localhost:8080"
basePath: "/ditas-project/DataUtilityEvaluator/0.2.1"
tags:
- name: "Data Utility"
  description: "Definition of data utility"
- name: "VDC-CAF"
  description: "Virtual Data Container CAF"
schemes:
- "https"
paths:
  /datautility:
    post:
      summary: "returns the data utility related to the data exposed through a CAF\
        \ method"
      description: "By passing one of the URL exposed by a CAF, the method returns\
        \ the data utility"
      operationId: "calculate_du"
      produces:
      - "application/json"
      parameters:
      - name: "method"
        in: "query"
        description: "URL of the method exposed by a data source"
        required: true
        type: "string"
        format: "url"
      - name: "attributes"
        in: "query"
        description: "list of attributes relevant for the user"
        required: false
        type: "array"
        items:
          type: "string"
      - in: "body"
        name: "filter"
        description: "list of pairs attributes, value (needs to be compatible with\
          \ Filter)"
        required: false
        schema:
          $ref: "#/definitions/Filter"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/DataUtility"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Filter:
    type: "object"
    properties:
      name:
        type: "string"
      value:
        type: "string"
    example:
      name: "name"
      value: "value"
  DataUtility:
    type: "object"
    required:
    - "URL"
    - "accuracy"
    - "completeness"
    - "consistency"
    - "timeliness"
    properties:
      URL:
        type: "string"
        format: "url"
        example: "http://mydatasource/pippo"
      accuracy:
        type: "number"
        format: "float"
        example: 0.1
      consistency:
        type: "number"
        format: "float"
        example: 0.1
      completeness:
        type: "number"
        format: "float"
        example: 0.1
      timeliness:
        type: "number"
        format: "float"
        example: 0.1
    example:
      timeliness: 0.1
      accuracy: 0.1
      completeness: 0.1
      consistency: 0.1
      URL: "http://mydatasource/pippo"
