---
swagger: "2.0"
info:
  description: "Data Utility Evaluator"
  version: "0.2.1"
  title: "Data Utility Evaluator"
  contact:
    email: "pierluigi.plebani@polimi.it"
  license:
    name: "TBD"
host: "localhost:8080"
basePath: "/"
tags:
- name: "Data Utility"
  description: "Definition of data utility"
- name: "VDC-CAF"
  description: "Virtual Data Container CAF"
schemes:
- "https"
paths:
  /v1/computeDataUtility:
    post:
      summary: "returns the data utility related to the data exposed through a CAF method"
      description: "By passing one of the Blueprint and the application requirement, the method returns the Blueprint with the data utility values calculated based on the application requirements"
      operationId: "calculate_du"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Input"
        required: true
        schema:
          $ref: "#/definitions/inputs"
      responses:
        200:
          description: "Blueprint updated"
          schema:
            $ref: "#/definitions/concreteBlueprint"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  inputs:
    properties:
      concreteBlueprint:
        $ref: "#/definitions/concreteBlueprint"
      methodName:
        type: string
  concreteBlueprint:
    properties:
      name:
        type: string
      tag:
        type: string
